### ISSUE TITLE
Simulator UI Fixes

### ISSUE THREAD

**Issue by bradleySuira** [yeagerai/genlayer-simulator#112]

**Comment by MuncleUscles** [comment]
- [ ] Code editor sometimes doesn't fill the screen
- [ ] Logs are not auto-scrolling

**Comment by MuncleUscles** [comment]
- [ ] Some Issue with Logs formatting when a long string was present ![image](https://github.com/yeagerai/genlayer-simulator/assets/2372232/6f70e885-f4f6-4254-9352-ff14b955bb92)

**Comment by MuncleUscles** [comment]
- [ ] Creating a validator should have all of the options of the "edit validator" modal, not just stake
- [ ] Edit validator doesn't have "Heurist" as a provider

**Comment by MuncleUscles** [comment]
- [ ] this list looks pretty janky, I don't think I care about the validator addresses here, let's take that out
![image](https://github.com/yeagerai/genlayer-simulator/assets/2372232/4b6b97ca-7e89-47d9-a6ef-cc7295eb8572)

**Comment by bradleySuira** [comment]
> * [x]  If i deploy a new version of a contract, and the currently selected method to execute has different parameters, the UI doesn't update until I switch to another method then back

this should be fixed in latest version

> * [ ]  Some Issue with Logs formatting when a long string was present ![image](https://private-user-images.githubusercontent.com/2372232/327532094-6f70e885-f4f6-4254-9352-ff14b955bb92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTU0MjEsIm5iZiI6MTcxNTMxNTEyMSwicGF0aCI6Ii8yMzcyMjMyLzMyNzUzMjA5NC02ZjcwZTg4NS1mNGY2LTQyNTQtOTM1Mi1mZjE0Yjk1NWJiOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMDQyNTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM3M2JhNWQ0NDAwN2I1NmJlYTk5ZDE2Mzc5OThhMzk2Yzk2OGU3ZjYwMGU2NWU0ODA2Yjk2ODA4MGVlZjg5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U0rF9RolGDpUPcF5dfvkCidSjxVHhAuAcsiuPOinfig)

fixed in latest from main
