### ISSUE TITLE
Python VSCode debugger breaks hot reload

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#145]
When we added the debugger to the genvm and the rpc server, the hot reload of the code stopped working. We need to find a way for it to work

**Comment by sevenearths** [comment]
`--debug` activate the hot reloader in Python => https://flask.palletsprojects.com/en/3.0.x/cli/#debug-mode
- Tried `--debug` with Flask in the Dcokerfile and in docker-compose.yml file. No success!
- Tried `wait-for-client` with debugpy. No success!
- Tried `use_reloader=True` in `socketio.run(...` at the bottom of rpc/server.py. No success!
- Picked up `"autoReload": {"enable": true},` as something we could using in the launch.json for VScode along the way.
