### ISSUE TITLE
SIM-Re-execute consensus when validators don't agree with the leader

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#168]

**Comment by AgustinRamiroDiaz** [comment]
@cristiam86 could you provide current behavior and desired behavior in the description?

**Comment by cristiam86** [comment]
Right now, in /backend/consensus/base.pyL169, when the consensus is not reached, an exception is raised.
Instead, it should select a new leader and execute the transaction again.
If all leaders have been rotated and there is still no consensus, the transaction is marked as undetermined: https://docs.google.com/document/d/1qUkQpR3urVNXJvlucmEfeOQJH510j7_XOqY-qDcXYT8/edit#heading=h.1nre5zseobfj
