### ISSUE TITLE
SIM-Logger results with json as json not strings

### ISSUE THREAD

**Issue by bradleySuira** [yeagerai/genlayer-simulator#172]
In some cases we are sending web socket messages with json objects but are sent as string and the logs ui render as is, we need to find a way to reuse the same log format in all cases when we need to send a json 

```
logger_result = {
            "function": self.function,
            "trace_id": self.trace_id,
            "response": result
        }

...
self.socketio_log(logger_result)
```

in the algorignt for example we send json objects inside string formated but in the ui are rendered as string 

![Image](https://github.com/yeagerai/genlayer-simulator/assets/1889891/149a1b7f-5e72-4fec-a949-7255480b5d67)

![Image](https://github.com/yeagerai/genlayer-simulator/assets/1889891/4eddd489-f2c1-456b-a4e3-d093a7876d56)

![Image](https://github.com/yeagerai/genlayer-simulator/assets/1889891/9de7835c-a965-4ac0-b925-2d165521c3e8)

**Comment by cristiam86** [comment]
With the new approach of the transactions transitions, this is no longer happening
