### ISSUE TITLE
SIM-GH Action to build docker images and push them to the registry on merge to main

### ISSUE THREAD

**Issue by sevenearths** [yeagerai/genlayer-simulator#223]

**Comment by sevenearths** [comment]
Problems with running tests on MacOS locally with act.

https://github.com/nektos/act/issues/97

**Comment by sevenearths** [comment]
Rabbit holes I went down while trying to get this to work on macos:
https://github.com/abiosoft/colima
https://blog.netnerds.net/2022/11/docker-macos-github-actions/
https://github.com/nektos/act/issues/97
https://github.com/ddev/ddev/blob/05ceed549d7807b1cebd63082910e54c37b1319e/.github/workflows/colima-tests.yml#L102-L106
https://github.com/abiosoft/colima/issues/905#issuecomment-2084457153
https://github.com/crazy-max/ghaction-setup-docker

**Comment by AgustinRamiroDiaz** [comment]
Closing in favor of https://github.com/yeagerai/genlayer-simulator/issues/319
