### ISSUE TITLE
SIM-problem parsing node configuration

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#233]
# Context

Environment https://github.com/yeagerai/genlayer-simulator/pull/229/commits/0801e972e734a4a3223ac2c0f84ea634df683a71

# Problem

While creating or editing a node, I get a `JSON.parse` error. This is a problem parsing the `config` section

**Comment by bradleySuira** [comment]
Was fixed in this PR [https://github.com/yeagerai/genlayer-simulator/pull/273](https://github.com/yeagerai/genlayer-simulator/pull/273)
