### ISSUE TITLE
SIM-Improve error feedback on contract code changes

### ISSUE THREAD

**Issue by bradleySuira** [yeagerai/genlayer-simulator#255]
When the code changes and we call "get contract schema" if there is an error, we:
1. Shouldn't show the toast with the error
2. Shouldn't hide the constructor parameters
3. Should Improve the message in the constructor parameters section
4. Disable the "Deploy" button while the code has errors

**Comment by bradleySuira** [comment]
In this case we spend some time trying to get the error details in the backend when execute contracts code and also try go render them in the front end, we found two main issues and one opportunity for refactor/improvement
Issues: 
- I found a way to get only in some cases the specific start/end line and start/end column of the code but not in all the exceptions
- In the front end side there is a method to render the errors and show a popover with the message / details but tried in different way and i't doesn't work

Opportunity for improvement/refactor
Currently we are creating an instance of the Monaco editor per file/contract, but now found that there is a possibility to use a single instance of the editor but creates a model per file, but it can take more time and maybe it can be the solution for render errors in the correct way (not 100% sure)

**Comment by cristiam86** [comment]
Comments from a duplicate issue: 
Review the ones generated here: https://github.com/yeagerai/genlayer-simulator/pull/140 and add a way to view them in the UI

**Comment by denishacquin** [comment]
Current state:



![Image](https://github.com/user-attachments/assets/5eeac8cd-1309-4f50-b76b-82f21a2a8f52)

@cristiam86 would that work for now? Having the highlighting + tooltips will be more tricky.

**Comment by cristiam86** [comment]
> Current state:
> 
> ![Image](https://private-user-images.githubusercontent.com/26140541/357838127-5eeac8cd-1309-4f50-b76b-82f21a2a8f52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDQxMzksIm5iZiI6MTcyMzY0MzgzOSwicGF0aCI6Ii8yNjE0MDU0MS8zNTc4MzgxMjctNWVlYWM4Y2QtMTMwOS00ZjUwLWI3NmItODJmMjFhMmE4ZjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEzNTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhODAyZWZiMjdhMWQwNDkyMDY3ZTZiZTJlNmEzZGUxYjk5ZmFlNTEzMmE2ZjNhMWI0YzIwMjBiNmFhNDkyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZXYDExDyytWrwjx4KynoKnfP3oMEn9RuacW-S_lq1E)
> 
> @cristiam86 would that work for now? Having the highlighting + tooltips will be more tricky.

YES! great!
