### ISSUE TITLE
SIM-BE-Refactor database connector to use SQLAlchemy

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#275]
# Context

Commented in https://github.com/yeagerai/genlayer-simulator/pull/234

# What

- Now that we have the db model in Python written with SQLAlchemy, we can use these datatypes instead of using dictionaries to improve the safety of our code
- We could also use SQLAlchemy to connect to the database and run the queries, so we can remove our custom `insert, update, delete` operations made with `psycopg2`
- Now it's also clearer to see that we are missing some things in the data model
  - some columns shouldn't be nullable
  - some columns should be FK references

# Why

- Higher levels of abstractions (`SQLAlchemy`) will allow us to worry less about implementation details of database connections (`psycopg2`)
- Schema changes will be easier to do by changing the `SQLAlchemy` models
- Schema will be easier to understand by just looking at the `SQLAlchemy` models

**Comment by cristiam86** [comment]
Example: https://github.com/yeagerai/genlayer-simulator/pull/307
