### ISSUE TITLE
SIM-Clear Latest transactions

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#281]
It seems that the not Finalized transactions in the queues remain there even after clearing the latest transaction list.
Also, let's remove the tx from the queue after receiving a "list index out of range" error.

**Comment by bradleySuira** [comment]
fixe in this PR [239-sim-fe-create-accounts-in-the-frontend-with-its-pair-of-keys](239-sim-fe-create-accounts-in-the-frontend-with-its-pair-of-keys)
