### ISSUE TITLE
SIM-Integrate Google Tag Manager

### ISSUE THREAD

**Issue by bradleySuira** [yeagerai/genlayer-simulator#287]

**Comment by denishacquin** [comment]
@cristiam86 do we have the GTM id already?

**Comment by cristiam86** [comment]
@denishacquin 

Here: GTM-T966KFPH

Also, it would be great if we can measure:
	- Different Contracts deployed
	- Total deployments
	- Methods called per contract
	- Total methods called
	- State reads per contract
	- Total state reads
	- Validators: number, provider, model

**Comment by denishacquin** [comment]
We probably also need to only enable it in production.

Another thing @cristiam86, I think typically GTM is event-based so I'm not sure if it makes sense trying to monitor state like so. For instance, we can have an event with **validator_created** with some params in it, but not sure if we can track something like **total_number_of_validators**.

Maybe we can find a different way to track such things like an analytics worker on a DB. Please tell me if I'm mistaken here :)

**Comment by cristiam86** [comment]
Changed to Plausible in #372
