### ISSUE TITLE
SIM-GH checks to block PRs from merging when tests don't pass

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#293]

**Comment by AgustinRamiroDiaz** [comment]
I've configured them and put them in Preview to test

**Comment by AgustinRamiroDiaz** [comment]
PR has been merged. I'll wait for a few days until enabling the GH Checks

**Comment by AgustinRamiroDiaz** [comment]
I'm waiting to enable this since some e2e tests are still not passing due to "no space left on disk" on some GH Actions

**Comment by cristiam86** [comment]
@AgustinRamiroDiaz great, I have asked @YeagerAI-Bulat to review his PR about the size of the docker images (https://github.com/yeagerai/genlayer-simulator/pull/238)
