### ISSUE TITLE
SIM-BE-Inconsistency on transaction ID paramaters

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#355]
Transaction ID inputs in requests to the backend are of type `str`, while Transaction ID return types are of type `int`

![image](https://github.com/user-attachments/assets/d29dcc7a-663a-4aa4-bedf-b111d697ea0f)

![image](https://github.com/user-attachments/assets/2ad6d09e-b90b-42e7-a18a-c9567101d8d4)

We should stick to either one of both
- `int` makes sense with SQL DB as the backend, but maybe `str` makes more sense in the crypto/blockchain environment

**Comment by cristiam86** [comment]
Solved with the transaction hash in https://github.com/yeagerai/genlayer-simulator/pull/479
