### ISSUE TITLE
CLI-Run simulator from Docker registry by default

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#358]
`genlayer init` and `genlayer up` should both run by default with the docker registry image

**Comment by cristiam86** [comment]
@AgustinRamiroDiaz, this is a CLI task, so the `docker-compose.yml` should be in that repo. As you are describing, the user should do `genlayer init` and it should download and execute the simulator directly from the docker images without having to checkout the repo or choose any branch. 
One thing to consider is the environment variables which the user needs to set in some way.

**Comment by AgustinRamiroDiaz** [comment]
moving to CLI https://github.com/yeagerai/genlayer-cli/issues/48
