### ISSUE TITLE
SIM-Refactor how inference providers are added and configured

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#359]
We need to make this more accessible and configurable.
Should it needs to be in the database and modified through some endpoints?

**Comment by cristiam86** [comment]
The main requirements are:
- We need to replace the current approach of having the JSON file with the providers, models, and default values.
- The providers, models, and default configuration should be stored in the database.
- We should provide endpoints for accessing the available providers and models (get_providers_and_models already exists), and to add new/edit/remove providers, models, and default configuration.
- The current process to create random validators should be refactored to use these values.
