### ISSUE TITLE
SIM-BE-Problems with imports on contract init

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#402]
# Steps to reproduce

```
from collections import defaultdict

def MyContract(IContract):
  def __init__(self):
    x = defaultdict
```

and then using that import in my contract's __init__ , my contract doesn't get deployed and gets stuck in `PROPOSING`

**Comment by cristiam86** [comment]
Closed due to the integration with the real GenVM
