### ISSUE TITLE
SIM-Providers are shown even if they are not configured

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#415]
# Context

When starting a fresh install or boot of the simulator, all default providers are shown even if they are not configured in the backend
![image](https://github.com/user-attachments/assets/d22d2fdd-ec9e-4600-ab2b-79a79afa99d6)

# Impact

Bad UX: This can be very counter intuitive for a user who creates a validator and then finds out through errors that the LLM provider is not configured in the backend

# Extra
Highly related to https://github.com/yeagerai/genlayer-simulator/issues/359

# Solution:
- Check availability for providers and models within the call to get_providers..
- Show unavailability in UI and educate user as to why

**Comment by denishacquin** [comment]
@AgustinRamiroDiaz we agree that we should probably wait for #359 before fixing this, right?

**Comment by AgustinRamiroDiaz** [comment]
@denishacquin yes!
