### ISSUE TITLE
SIM-GH Action to validate PR title and content

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#423]
Actions:
- Validate PR title is a conventional commit
- It complies with the PR template
- It should be pointing to staging

**Comment by AgustinRamiroDiaz** [comment]
@cristiam86 I think that checking that the PR body complies with the PR template is very hard, since the solutions that I'm thinking of would be very brittle (checking for certain words in the body)

I think that would be a feature we could implement with an intelligent contract to leverage LLMs. I'd leave that part for later

**Comment by cristiam86** [comment]
> @cristiam86 I think that checking that the PR body complies with the PR template is very hard, since the solutions that I'm thinking of would be very brittle (checking for certain words in the body)
> 
> I think that would be a feature we could implement with an intelligent contract to leverage LLMs. I'd leave that part for later

What about a regex? like this one: https://github.com/yeagerai/hackathon-2024-08-16/blob/main/DeepThoughtCoders/adr_validator.py#L68

**Comment by AgustinRamiroDiaz** [comment]
> > @cristiam86 I think that checking that the PR body complies with the PR template is very hard, since the solutions that I'm thinking of would be very brittle (checking for certain words in the body)
> > I think that would be a feature we could implement with an intelligent contract to leverage LLMs. I'd leave that part for later
> 
> What about a regex? like this one: https://github.com/yeagerai/hackathon-2024-08-16/blob/main/DeepThoughtCoders/adr_validator.py#L68

Well we can do that to check the headers, but I'm not sure if that's valuable. I feel that we'll be leaving empty sections just to adhere with the regex, and that might not be valuable

**Comment by cristiam86** [comment]
> > > @cristiam86 I think that checking that the PR body complies with the PR template is very hard, since the solutions that I'm thinking of would be very brittle (checking for certain words in the body)
> > > I think that would be a feature we could implement with an intelligent contract to leverage LLMs. I'd leave that part for later
> > 
> > 
> > What about a regex? like this one: https://github.com/yeagerai/hackathon-2024-08-16/blob/main/DeepThoughtCoders/adr_validator.py#L68
> 
> Well we can do that to check the headers, but I'm not sure if that's valuable. I feel that we'll be leaving empty sections just to adhere with the regex, and that might not be valuable

ok, let's keep it as it is and look for an AI tool then :) something like https://github.com/Codium-ai/pr-agent 

btw, having empty sections just with the titles will bring all the shame on you :D
