### ISSUE TITLE
SIM-BE- Add HealthCheck to backend container

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#428]
We should add a healthcheck to the backend container:
- so we can depend on
- so we can monitor the server's status

I'm talking particularly about [Docker healthchecks](https://docs.docker.com/reference/dockerfile/#healthcheck), which can be also implemented in the `docker-compose.yml`

**Comment by cristiam86** [comment]
Fixed in: https://github.com/yeagerai/genlayer-simulator/pull/564
