### ISSUE TITLE
Refactor RPC endpoints

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#432]
We need to do some refactor on the following endpoints to match the Ethereum specs: (backend/protocol_rpc/endpoints.py)
- create_account: remove it and comment its usage on every place
- send_transaction: remove it and comment its usage on every place
- get_contract_state: rename it to call and change the parameters to match the Ethereum specification here: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call. Also, note that the frontend serialization (and maybe the signing should be also considered)

**Comment by denishacquin** [comment]
should the `fund_account`also be removed?

**Comment by cristiam86** [comment]
> should the `fund_account`also be removed?

nop, that one we will use it.

**Comment by denishacquin** [comment]
I opened a draft PR here:
https://github.com/yeagerai/genlayer-simulator/pull/481/files

Which covers the removal of the two first endpoints as well as the renaming of the third.

However, I would need us to chat for the spec matching / frontend serialization stuff to gain some clarity on that @cristiam86
