### ISSUE TITLE
Return validator execution logs

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#436]

**Comment by denishacquin** [comment]
Please tell me if I understand correctly: we want to print the validator execution logs in the logs panel in the UI?

![Image](https://github.com/user-attachments/assets/356fef06-dbec-4c5d-a4c9-2c746949776b)

**Comment by cristiam86** [comment]
I would like to inform the user about what's happening in the consensus.
The first thing that comes to my mind is the changes in the transaction status. Currently, you can see the status of the transaction in the latest list, but not all the state transitions. 
Also, it would be nice to get in the logs when the vote has been processed and its outcome. 
It could also be nice to know when the validators are calling an LLM or requesting the content of a website, but this could also be more complicated to achieve.
