### ISSUE TITLE
Allow async calls in the contract constructor

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#449]
# Issue

This is a problem for contracts that want to call async functions in init methods, like LLM calls

this seems to be an issue related to coroutines: [the code instantiates the class](https://github.com/yeagerai/genlayer-simulator/blob/7f296f3eb6546fd05578174d174c131a31bb6f93/backend/node/genvm/base.py#L120) as is, but in order to actually call the llm you need to make init method async, which means that now the class' init needs to be awaited

# Some ideas
a) try and reuse the asyncio event loop to call class __init__ methods with asyncio
b) handle both async and sync __init__ in the simulator

In general people don't recommend using async inits, so maybe we need to expose the asyncio event loop in some way

**Comment by AgustinRamiroDiaz** [comment]
Exploring this issue:

I've found that we can access the asyncio event loop from within the contracts
```py
        loop = asyncio.get_running_loop()
        task = loop.create_task(self.test())
        asyncio.gather(task)

        async def test(self):
            pass
```

**Comment by cristiam86** [comment]
Can the constructor call another async method? If so, could we change this under the hood and add another __init2_function that is always and only called from the constructor?

**Comment by kp2pml30** [comment]
Does the following work for you?
```py
import asyncio
def foo():
    task = asyncio.run(test())
    print(f'task={task}')

async def test():
    import time
    time.sleep(0.5)
    return 1

foo()
```
Output is
```
task=1
```
Exit code is 0

(Works in constructor as well)

**Comment by AgustinRamiroDiaz** [comment]
@kp2pml30 thanks for the feedback! the example you provide works if I run it in a `main.py` file by its own

The thing is that inside the simulator, the construction of the class is done inside an asyncio loop, so trying that out outputs

```
Intelligent Contract Execution Log ===> asyncio.run() cannot be called from a running event loop ;; Traceback (most recent call last): File "/app/backend/node/genvm/base.py", line 126, in deploy_contract current_contract = contract_class(**constructor_args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 8, in __init__ File "/usr/local/lib/python3.12/asyncio/runners.py", line 190, in run raise RuntimeError( RuntimeError: asyncio.run() cannot be called from a running event loop 
```

Do you know if there's a way to use the current event loop syncronously like with `asyncio.run`?
