### ISSUE TITLE
Refactor transaction id with transaction Hash

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#451]
The current transaction ID is a postgress auto-incremental ID that should be changed to the transaction HASH.
This also affects the endpoint "get_transaction_by_id" which should be changed to "get_transaction_by_hash"
In the frontend list, the ID can be changed to the transaction hash's last 4 or 6 characters.

**Comment by denishacquin** [comment]
A few questions come to mind:

- we need to implement a way to generate transaction hashes, correct?
- should the ID column disappear altogether?
- migration: should we generate hashes for all existing TX or should we not care about legacy data?

**Comment by cristiam86** [comment]
- we need to implement a way to generate transaction hashes, correct?
We should research how Ethereum does it, which fields are included and the hash algorithm used.

- should the ID column disappear altogether?
It would be the best solution if the primary key could be the transaction hash

- migration: should we generate hashes for all existing TX or should we not care about legacy data?
It would be the best.

**Comment by denishacquin** [comment]
Opened a draft PR here: #479 

Would you kindly have a look and let me know if that seems to be on the right track @cristiam86 ?
