### ISSUE TITLE
Contract-to-contract write

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#454]
Allow to send a transaction from one contract to another contract

**Comment by AgustinRamiroDiaz** [comment]
Based on https://docs.google.com/document/d/1qUkQpR3urVNXJvlucmEfeOQJH510j7_XOqY-qDcXYT8/edit#heading=h.jdxv42hmj9qs

We should be able to call something like

```
Contract("0x123").send_message(on_finalized_or_on_accepted, value, "func_to_call", **args)
```
---

Node Receipts should return two arrays containing the on_finalized and on_accepted pending transactions, which will be processed in the consensus `exec_transaction` when the transaction reaches those states
