### ISSUE TITLE
SIM-FE Don't let the user call LLMs when there's no API key

### ISSUE THREAD

**Issue by denishacquin** [yeagerai/genlayer-simulator#488]
Openai error: invalid auth key format

https://www.loom.com/share/476d4de4fbfd4af2a7a1bdbe898b7902?sid=28de1c79-2cae-40e9-9969-128e771fae84

Seems like he hadn't set up an API key :confused:
OpenAIException - Error submitting job heurist-llm-gatewayrpqhveqsls: Unhandled rejection: CustomError { message: "Invalid auth_key format" }

Maybe we could improve UX warning user in the UI when the API keys are not set up.

**Comment by denishacquin** [comment]
![Image](https://github.com/user-attachments/assets/0f184aaa-f2ac-4ccd-b360-e9c397084cd0)

**Comment by cristiam86** [comment]
With #359 this is probably solved

**Comment by denishacquin** [comment]
We have added some error handling as part of #562 to flag this scenario:

![Image](https://github.com/user-attachments/assets/f15a5434-f2f8-4dfa-8264-67c14372f250)
![Image](https://github.com/user-attachments/assets/a4190f5b-8b8f-4a73-abf3-7d9eb37638d4)

**Comment by cristiam86** [comment]
Great! Closing this issue in favor of #562
