### ISSUE TITLE
SIM-FE-Encoding of complex types in functions is not working properly

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#549]
We don't handle correctly complex types like `dict` or `list`, they are handled as strings

![image](https://github.com/user-attachments/assets/196de4df-e9c4-4f6a-b30d-db4067ac9a08)

![image](https://github.com/user-attachments/assets/ec4c9a90-7f12-487a-9676-c0c200f4d094)

**Comment by cristiam86** [comment]
Closed due to the integration with the real GenVM
