### ISSUE TITLE
SIM-Studio renaming and exceptions

### ISSUE THREAD

**Issue by denishacquin** [yeagerai/genlayer-simulator#590]
We need to:

- Hide UI related to adding validators when on hosted environment
- Adapt the routing to remove the simulator subpath `https://studio.genlayer.com/simulator/run-debug`
- Gatekeep or disable sensitive endpoints
- Update the plausible domains to studio.genlayer.com (both in codebase + in plausible)
- Adapt copy where necessary
- Update the Docs

**Comment by denishacquin** [comment]
Will we be changing the repo name? @cristiam86

**Comment by denishacquin** [comment]
Also, regarding the validators, obviously we want to hide stuff related to editing them - but do we want to display them at all?
<img width="605" alt="image" src="https://github.com/user-attachments/assets/c18127e4-592d-4d80-a67b-7afd88e704d6">

**Comment by AgustinRamiroDiaz** [comment]
@denishacquin if it's not too much trouble, I think read only operations on the validators would be nice to have

**Comment by denishacquin** [comment]
> @denishacquin if it's not too much trouble, I think read only operations on the validators would be nice to have

You mean keeping the read endpoints open? Or also displaying the validators in the UI but just not allow to add any?
