### ISSUE TITLE
SIM-FE hanging of the status in left panel 

### ISSUE THREAD

**Issue by kstroobants** [yeagerai/genlayer-simulator#605]
Simulator frontend: Hanging of the status in left panel and not seeing get function buttons. Sometimes refresh solves it. It occurs more than 50% of the time. I only tried deploying a contract. No idea if it also happens when doing other transactions.

Could be my chrome browser but it should not matter. I cleared also my cache and I still see the issue. Maybe clear your browser's cache if you cannot replicate it.

The issue was added in one of the following commits. I worked on earlier commits where I did not see this:
4f1f948 (tag: v0.20.0, origin/main, origin/HEAD, main) fix: hide methods during deployment to avoid pointing to the wrong contract instance (#582)
771db2a feat: update transactions based on subscriptions events and remove polling (#583)
cb516e4 updated GH actions workflow (#597)
b3e83d0 (tag: v0.19.0) feat: allow configuring validators from envvar (#585)
1e66f9d feat: integrate OpenHands for automatic code generation from GitHub issues (#576) (#578)

wizard of coin stuck:
![wizard_of_coin_stuck](https://github.com/user-attachments/assets/aa8c9617-ba2e-4ec2-a94f-a2ada0b1dc52)

wizard of coin resolved after refreshing the browser (0x0319.. is the same and logs show refresh):
![wizard_of_coin_reshed_solved](https://github.com/user-attachments/assets/26be0e0d-40de-42b7-ac8e-1dc4e999b4a9)

llm erc20 stuck on accepted, same as wizard of coin so it is not contract dependent:
![llm_erc20_1_stuck](https://github.com/user-attachments/assets/9a43ec37-47a6-4e0f-9c82-63bb9b7b127e)

llm erc20 new deployment, stuck again but on finalized. No get methods visible:
![llm_erc20_2_stuck_on_finalized_no_get_methods](https://github.com/user-attachments/assets/66975644-6fe9-4ca2-861a-ea934477c395)

llm erc20 refresh of browser shows no deployment, but in list there is a deployed contract (number is same as previous picture):
![llm_erc20_2_refresh_of_finalized_shows_no_deployment_but_in_list_there_is_a_deploy](https://github.com/user-attachments/assets/335bc49f-a057-4b49-8523-85e0fdd0e577)

**Comment by kstroobants** [comment]
Solved in PR #589 by adding session.commit() whenever the status of a transaction is changed

**Comment by denishacquin** [comment]
Just saw this was solved already. Not sure the frontend fix I came up with is still relevant then. I worked from the assumption that we had concurrency issues when receiving fast fired websocket events - Maybe we can keep it on the side if a similar symptom arises again.

**Comment by kstroobants** [comment]
Yes, sorry. I was not expecting it to be related to updating the databases more often. I like the improvement compared to two weeks ago a lot. It is super smooth.

Your PR looks good to have but I don't know if it has side-effects.
