### ISSUE TITLE
Get Providers and Models from JsonRPC endpoint for validator settings

### ISSUE THREAD

**Issue by bradleySuira** [yeagerai/genlayer-simulator#83]
We required an endpoint to retrieve the list of providers and models associated to render them in the update validator settings form, actually we have this values /schema in the frontend

```
{
    "openai": [
        "gpt-3.5-turbo",
        "gpt-4"
    ],
    "ollama": [
        "llama2",
        "gemma",
        "mistral",
        "mixtral",
        "gpt-4"
    ]
}
```

**Comment by cristiam86** [comment]
@bradleySuira @sevenearths isn't this done?

**Comment by bradleySuira** [comment]
> @bradleySuira @sevenearths isn't this done?

will check with @sevenearths I have another issue related to create validators screen

**Comment by sevenearths** [comment]
@cristiam86  @bradleySuira This has already been done here => https://github.com/yeagerai/genlayer-simulator/blob/main/rpc/server.py#L606
